msg-shedule:
  scheduler: # 调度组件
    # 线程池配置
    schedule-executor:
      min-thread: 2
      max-thread: 2
    checkpoint-executor:
      min-thread: 2
      max-thread: 2
    default-schedule-delay:
      checkpoint-delay: 30 # 默认不写30分钟维护一次，route中不写默认以此值为默认值
      load-delay: 30 # 默认不写30分钟维护一次，route中不写默认以此值为默认值
    route: # 表与调度组件关系
      load-from-repository: true # 配置后，需要调度的表从 MessageRepository 实现类获取，tables中仅作为调度参数；当false时，调度的table对象从tables属性中获取，未指出的不调度。
      tables:
        msgTableA: # 消息表名，仓储层将实现接口与此对应
          checkpoint-schedule-delay: 30 # 30分钟维护一次
          load-schedule-delay: 30 # 30分钟调度一次；对于延时消息，预加载30分钟的内容或检查点到格式化时间的内容；对于事务消息，前置检查30分钟的消息或检查点到当前时间；
        msgTableB:
          checkpoint-schedule-delay: 30
          load-schedule-delay: 30
        msgTableC: # 不指定，就遵从默认配置。
        msgTableD:
  message-queue: # 配置平台实现
    rocketmq:
      name-server: "nameServer"
      producers:
        common-producer:
          # common topic，具体业务使用tags
          group: common-producer-group
          name-server: "nameServer"
          instance-name: "instance-name"